created the pickup-dropoff component
moath-dawood/RentMyRide pull request #2
Opened 2023-05-21 19:53 UTC by moath-dawood

2023-05-22 11:44 UTC, baha-ott commented on src/Components/Homepage/index.js
>      <div>
main elements instead of div

2023-05-22 11:57 UTC, baha-ott commented on src/Components/PickupCard/Dropoff.js
> +import * as React from 'react';
no need to import everything, just import what you want to use

2023-05-22 11:58 UTC, baha-ott commented on src/Components/PickupCard/Dropoff.js
> +import { Box, Typography, CardMedia, Grid } from '@mui/material';
remove things that you are not using, such as Box

2023-05-22 12:01 UTC, baha-ott commented on src/Components/PickupCard/Dropoff.js
> +const names = [
cityNames

2023-05-22 12:05 UTC, baha-ott commented on src/Components/PickupCard/Dropoff.js
> +                        if (selected.length === 0) {
use ternary operator

2023-05-22 12:08 UTC, baha-ott requested changes
divide components more better pls! 
Good job moath, have a nice work !

2023-05-23 10:38 UTC, moath-dawood commented
> divide components more better pls! Good job moath, have a nice work !

Will do better in next components, its clustered like this because its a premade component from mui.

2023-05-23 11:55 UTC, baha-ott approved these changes

2023-05-24 09:54 UTC, merged